[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true
